# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

admin_dashboard:
  url: /admin/dashboard
  param: { module: admin, action: dashboard }

feeds_podcast:
  url: /feeds/podcast
  param: {module: feeds, action: podcast }

feeds_events:
  url: /feeds/events
  param: {module: feeds, action: events }

ego_list:
  url: /ego
  param: { module: ego, action: list }

# default rules
homepage:
  url:   /
  param: { module: test, action: index }