<?php

/**
 * LUM_SellableTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_SellableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_SellableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Sellable');
    }
}