<?php

/**
 * LUM_DiscussionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LUM_DiscussionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LUM_DiscussionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LUM_Discussion');
    }

    /**
     * Returns latest discussions.
     *
     * @return array[LUM_Discussion]
     */
    public function getLatest($limit = 50)
    {
        // Build query
        $q = $this->createQuery()
            ->select()
            ->where('Active = 1')
            ->andWhere('Closed != 1')
            ->andWhere('Sink != 1')
            ->andWhere('WhisperUserID = 0')
            ->limit($limit)
            ->orderBy('DateLastActive DESC');

        // Fetch discussions
        $discussions = $q->execute();

        // Return results
        return $discussions;
    }
}