<?php

/**
 * LUM_Discussion
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    musiques-incongrues
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LUM_Discussion extends BaseLUM_Discussion
{
    /**
     * Returns discussion's URI.
     *
     * @return string
     */
    public function getUri($prefix = '')
    {
        return sprintf('%s/%d/%s', $prefix, $this->discussionid, $this->getSlug());
    }

    /**
     * Generates discussion slug.
     *
     * @return slug
     *
     * @see http://www.intrepidstudios.com/blog/2009/2/10/function-to-generate-a-url-friendly-string.aspx
     */
    public function getSlug()
    {
        // Build slug
        $result = strtolower($this->name);

        $result = preg_replace("/[^a-z0-9\s-]/", "", $result);
        $result = trim(preg_replace("/[\s-]+/", " ", $result));
        $result = preg_replace("/\s/", "-", $result);

        return $result;
    }
}
