<?php
// Enabled Extensions
include($Configuration['EXTENSIONS_PATH']."Audioscrobbler/default.php");
include($Configuration['EXTENSIONS_PATH']."GuestWelcome/default.php");
include($Configuration['EXTENSIONS_PATH']."GoogleAnalytics/default.php");
include($Configuration['EXTENSIONS_PATH']."WhisperNotification/default.php");
include($Configuration['EXTENSIONS_PATH']."Atom/default.php");
include($Configuration['EXTENSIONS_PATH']."RSS2/default.php");
include($Configuration['EXTENSIONS_PATH']."GuestPost/default.php");
include($Configuration['EXTENSIONS_PATH']."ForcedBBCode/default.php");
include($Configuration['EXTENSIONS_PATH']."Vanillacons/default.php");
include($Configuration['EXTENSIONS_PATH']."PreviewPost/default.php");
include($Configuration['EXTENSIONS_PATH']."Quotations/default.php");
include($Configuration['EXTENSIONS_PATH']."JQuery/default.php");
include($Configuration['EXTENSIONS_PATH']."JQmedia/default.php");
include($Configuration['EXTENSIONS_PATH']."Statistics/default.php");
include($Configuration['EXTENSIONS_PATH']."vanilla-events/default.php");
include($Configuration['EXTENSIONS_PATH']."vanilla-releases/default.php");
include($Configuration['EXTENSIONS_PATH']."MetaTags/default.php");
include($Configuration['EXTENSIONS_PATH']."vanilla-alaune/default.php");
include($Configuration['EXTENSIONS_PATH']."vanilla-visuels/default.php");
include($Configuration['EXTENSIONS_PATH']."PageMng/default.php");
include($Configuration['EXTENSIONS_PATH']."vanilla-player/default.php");
//include($Configuration['EXTENSIONS_PATH']."vanilla-shop/default.php");
include($Configuration['EXTENSIONS_PATH']."comments_permalinks/default.php");
include($Configuration['EXTENSIONS_PATH']."MembersList/default.php");
include($Configuration['EXTENSIONS_PATH']."SubCategories/default.php");
include($Configuration['EXTENSIONS_PATH']."vanilla-symfony/default.php");
include($Configuration['EXTENSIONS_PATH']."DiscussionFilters/default.php");
include($Configuration['EXTENSIONS_PATH']."MiProjects/default.php");
include($Configuration['EXTENSIONS_PATH']."MiSidebar/default.php");
include($Configuration['EXTENSIONS_PATH']."MiRandomDiscussion/default.php");
include($Configuration['EXTENSIONS_PATH']."MiBase/default.php");
include($Configuration['EXTENSIONS_PATH']."MiBetaTesting/default.php");
include($Configuration['EXTENSIONS_PATH']."MiOpengraph/default.php");
include($Configuration['EXTENSIONS_PATH']."MiVanillaMiner/default.php");
?>
