var arrSmilies = [];
arrSmilies["Assi Pychaf - Zoo Incongru"] = [];
arrSmilies["Assi Pychaf - Zoo Incongru"][0] = '<span onclick="insertSmilie(\'zooincongru1.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Assi Pychaf - Zoo Incongru/zooincongru1.gif" /></span>';
arrSmilies["Assi Pychaf - Zoo Incongru"][1] = '<span onclick="insertSmilie(\'zooincongru2.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Assi Pychaf - Zoo Incongru/zooincongru2.png" /></span>';
arrSmilies["Assi Pychaf - Zoo Incongru"][2] = '<span onclick="insertSmilie(\'zooincongru3.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Assi Pychaf - Zoo Incongru/zooincongru3.png" /></span>';
arrSmilies["Assi Pychaf - Zoo Incongru"][3] = '<span onclick="insertSmilie(\'zooincongru4.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Assi Pychaf - Zoo Incongru/zooincongru4.png" /></span>';
arrSmilies["Assi Pychaf - Zoo Incongru"][4] = '<span onclick="insertSmilie(\'zooincongru5.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Assi Pychaf - Zoo Incongru/zooincongru5.png" /></span>';
arrSmilies["Assi Pychaf - Zoo Incongru"][5] = '<span onclick="insertSmilie(\'zooincongru6.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Assi Pychaf - Zoo Incongru/zooincongru6.png" /></span>';
arrSmilies["bood - lofi"] = [];
arrSmilies["bood - lofi"][0] = '<span onclick="insertSmilie(\'01.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/01.gif" /></span>';
arrSmilies["bood - lofi"][1] = '<span onclick="insertSmilie(\'02.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/02.gif" /></span>';
arrSmilies["bood - lofi"][2] = '<span onclick="insertSmilie(\'03.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/03.gif" /></span>';
arrSmilies["bood - lofi"][3] = '<span onclick="insertSmilie(\'04.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/04.gif" /></span>';
arrSmilies["bood - lofi"][4] = '<span onclick="insertSmilie(\'05.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/05.gif" /></span>';
arrSmilies["bood - lofi"][5] = '<span onclick="insertSmilie(\'06.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/06.gif" /></span>';
arrSmilies["bood - lofi"][6] = '<span onclick="insertSmilie(\'07.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/07.gif" /></span>';
arrSmilies["bood - lofi"][7] = '<span onclick="insertSmilie(\'08.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/08.gif" /></span>';
arrSmilies["bood - lofi"][8] = '<span onclick="insertSmilie(\'09.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/09.gif" /></span>';
arrSmilies["bood - lofi"][9] = '<span onclick="insertSmilie(\'10.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/10.gif" /></span>';
arrSmilies["bood - lofi"][10] = '<span onclick="insertSmilie(\'11.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/11.gif" /></span>';
arrSmilies["bood - lofi"][11] = '<span onclick="insertSmilie(\'12.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/12.gif" /></span>';
arrSmilies["bood - lofi"][12] = '<span onclick="insertSmilie(\'13.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/13.gif" /></span>';
arrSmilies["bood - lofi"][13] = '<span onclick="insertSmilie(\'14.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/14.gif" /></span>';
arrSmilies["bood - lofi"][14] = '<span onclick="insertSmilie(\'15.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/15.gif" /></span>';
arrSmilies["bood - lofi"][15] = '<span onclick="insertSmilie(\'16.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/16.gif" /></span>';
arrSmilies["bood - lofi"][16] = '<span onclick="insertSmilie(\'17.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/17.gif" /></span>';
arrSmilies["bood - lofi"][17] = '<span onclick="insertSmilie(\'18.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/18.gif" /></span>';
arrSmilies["bood - lofi"][18] = '<span onclick="insertSmilie(\'19.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/19.gif" /></span>';
arrSmilies["bood - lofi"][19] = '<span onclick="insertSmilie(\'20.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/20.gif" /></span>';
arrSmilies["bood - lofi"][20] = '<span onclick="insertSmilie(\'21.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/21.gif" /></span>';
arrSmilies["bood - lofi"][21] = '<span onclick="insertSmilie(\'22.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/22.gif" /></span>';
arrSmilies["bood - lofi"][22] = '<span onclick="insertSmilie(\'23.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/23.gif" /></span>';
arrSmilies["bood - lofi"][23] = '<span onclick="insertSmilie(\'24.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/24.gif" /></span>';
arrSmilies["bood - lofi"][24] = '<span onclick="insertSmilie(\'25.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/25.gif" /></span>';
arrSmilies["bood - lofi"][25] = '<span onclick="insertSmilie(\'26.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/26.gif" /></span>';
arrSmilies["bood - lofi"][26] = '<span onclick="insertSmilie(\'27.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/27.gif" /></span>';
arrSmilies["bood - lofi"][27] = '<span onclick="insertSmilie(\'28.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/28.gif" /></span>';
arrSmilies["bood - lofi"][28] = '<span onclick="insertSmilie(\'29.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/29.gif" /></span>';
arrSmilies["bood - lofi"][29] = '<span onclick="insertSmilie(\'30.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/30.gif" /></span>';
arrSmilies["bood - lofi"][30] = '<span onclick="insertSmilie(\'31.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/31.gif" /></span>';
arrSmilies["bood - lofi"][31] = '<span onclick="insertSmilie(\'32.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/32.gif" /></span>';
arrSmilies["bood - lofi"][32] = '<span onclick="insertSmilie(\'33.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/33.gif" /></span>';
arrSmilies["bood - lofi"][33] = '<span onclick="insertSmilie(\'34.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/34.gif" /></span>';
arrSmilies["bood - lofi"][34] = '<span onclick="insertSmilie(\'35.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/35.gif" /></span>';
arrSmilies["bood - lofi"][35] = '<span onclick="insertSmilie(\'36.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/36.gif" /></span>';
arrSmilies["bood - lofi"][36] = '<span onclick="insertSmilie(\'37.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/37.gif" /></span>';
arrSmilies["bood - lofi"][37] = '<span onclick="insertSmilie(\'38.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/38.gif" /></span>';
arrSmilies["bood - lofi"][38] = '<span onclick="insertSmilie(\'39.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/39.gif" /></span>';
arrSmilies["bood - lofi"][39] = '<span onclick="insertSmilie(\'40.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/40.gif" /></span>';
arrSmilies["bood - lofi"][40] = '<span onclick="insertSmilie(\'41.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/41.gif" /></span>';
arrSmilies["bood - lofi"][41] = '<span onclick="insertSmilie(\'42.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/42.gif" /></span>';
arrSmilies["bood - lofi"][42] = '<span onclick="insertSmilie(\'43.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/43.gif" /></span>';
arrSmilies["bood - lofi"][43] = '<span onclick="insertSmilie(\'44.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/44.gif" /></span>';
arrSmilies["bood - lofi"][44] = '<span onclick="insertSmilie(\'46.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/46.gif" /></span>';
arrSmilies["bood - lofi"][45] = '<span onclick="insertSmilie(\'47.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/47.gif" /></span>';
arrSmilies["bood - lofi"][46] = '<span onclick="insertSmilie(\'48.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/48.gif" /></span>';
arrSmilies["bood - lofi"][47] = '<span onclick="insertSmilie(\'49.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - lofi/49.gif" /></span>';
arrSmilies["bood - me"] = [];
arrSmilies["bood - me"][0] = '<span onclick="insertSmilie(\'50.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/50.gif" /></span>';
arrSmilies["bood - me"][1] = '<span onclick="insertSmilie(\'51.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/51.gif" /></span>';
arrSmilies["bood - me"][2] = '<span onclick="insertSmilie(\'52.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/52.gif" /></span>';
arrSmilies["bood - me"][3] = '<span onclick="insertSmilie(\'54.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/54.gif" /></span>';
arrSmilies["bood - me"][4] = '<span onclick="insertSmilie(\'56.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/56.gif" /></span>';
arrSmilies["bood - me"][5] = '<span onclick="insertSmilie(\'57.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/57.gif" /></span>';
arrSmilies["bood - me"][6] = '<span onclick="insertSmilie(\'58.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/58.gif" /></span>';
arrSmilies["bood - me"][7] = '<span onclick="insertSmilie(\'59.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/59.gif" /></span>';
arrSmilies["bood - me"][8] = '<span onclick="insertSmilie(\'60.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/60.gif" /></span>';
arrSmilies["bood - me"][9] = '<span onclick="insertSmilie(\'61.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/61.gif" /></span>';
arrSmilies["bood - me"][10] = '<span onclick="insertSmilie(\'62.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/62.gif" /></span>';
arrSmilies["bood - me"][11] = '<span onclick="insertSmilie(\'63.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/63.gif" /></span>';
arrSmilies["bood - me"][12] = '<span onclick="insertSmilie(\'64.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/64.gif" /></span>';
arrSmilies["bood - me"][13] = '<span onclick="insertSmilie(\'65.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/65.gif" /></span>';
arrSmilies["bood - me"][14] = '<span onclick="insertSmilie(\'66.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/66.gif" /></span>';
arrSmilies["bood - me"][15] = '<span onclick="insertSmilie(\'67.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/67.gif" /></span>';
arrSmilies["bood - me"][16] = '<span onclick="insertSmilie(\'68.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/68.gif" /></span>';
arrSmilies["bood - me"][17] = '<span onclick="insertSmilie(\'69.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/69.gif" /></span>';
arrSmilies["bood - me"][18] = '<span onclick="insertSmilie(\'70.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/70.gif" /></span>';
arrSmilies["bood - me"][19] = '<span onclick="insertSmilie(\'71.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/71.gif" /></span>';
arrSmilies["bood - me"][20] = '<span onclick="insertSmilie(\'72.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/72.gif" /></span>';
arrSmilies["bood - me"][21] = '<span onclick="insertSmilie(\'73.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/73.gif" /></span>';
arrSmilies["bood - me"][22] = '<span onclick="insertSmilie(\'74.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/74.gif" /></span>';
arrSmilies["bood - me"][23] = '<span onclick="insertSmilie(\'75.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/75.gif" /></span>';
arrSmilies["bood - me"][24] = '<span onclick="insertSmilie(\'76.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/76.gif" /></span>';
arrSmilies["bood - me"][25] = '<span onclick="insertSmilie(\'78.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/78.gif" /></span>';
arrSmilies["bood - me"][26] = '<span onclick="insertSmilie(\'79.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/79.gif" /></span>';
arrSmilies["bood - me"][27] = '<span onclick="insertSmilie(\'80.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/80.gif" /></span>';
arrSmilies["bood - me"][28] = '<span onclick="insertSmilie(\'81.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/81.gif" /></span>';
arrSmilies["bood - me"][29] = '<span onclick="insertSmilie(\'82.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/82.gif" /></span>';
arrSmilies["bood - me"][30] = '<span onclick="insertSmilie(\'83.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/83.gif" /></span>';
arrSmilies["bood - me"][31] = '<span onclick="insertSmilie(\'84.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/84.gif" /></span>';
arrSmilies["bood - me"][32] = '<span onclick="insertSmilie(\'85.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/85.gif" /></span>';
arrSmilies["bood - me"][33] = '<span onclick="insertSmilie(\'86.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/86.gif" /></span>';
arrSmilies["bood - me"][34] = '<span onclick="insertSmilie(\'87.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/87.gif" /></span>';
arrSmilies["bood - me"][35] = '<span onclick="insertSmilie(\'88.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/88.gif" /></span>';
arrSmilies["bood - me"][36] = '<span onclick="insertSmilie(\'89.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/bood - me/89.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"] = [];
arrSmilies["organic - Sons of the Ananas"][0] = '<span onclick="insertSmilie(\'pin-3D2.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-3D2.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][1] = '<span onclick="insertSmilie(\'pin-3D.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-3D.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][2] = '<span onclick="insertSmilie(\'pin-acid.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-acid.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][3] = '<span onclick="insertSmilie(\'pin-adolf.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-adolf.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][4] = '<span onclick="insertSmilie(\'pin-biere.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-biere.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][5] = '<span onclick="insertSmilie(\'pin-bimbim.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-bimbim.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][6] = '<span onclick="insertSmilie(\'pin-bisou.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-bisou.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][7] = '<span onclick="insertSmilie(\'pin-bitnik.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-bitnik.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][8] = '<span onclick="insertSmilie(\'pin-blink.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-blink.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][9] = '<span onclick="insertSmilie(\'pin-bob.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-bob.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][10] = '<span onclick="insertSmilie(\'pin-bob-stache.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-bob-stache.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][11] = '<span onclick="insertSmilie(\'pin-boobs.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-boobs.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][12] = '<span onclick="insertSmilie(\'pin-bouffon.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-bouffon.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][13] = '<span onclick="insertSmilie(\'pin-bravo.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-bravo.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][14] = '<span onclick="insertSmilie(\'pin-burp.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-burp.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][15] = '<span onclick="insertSmilie(\'pin-cagoule.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-cagoule.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][16] = '<span onclick="insertSmilie(\'pin-caillasse.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-caillasse.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][17] = '<span onclick="insertSmilie(\'pin-centipede.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-centipede.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][18] = '<span onclick="insertSmilie(\'pin-cerf.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-cerf.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][19] = '<span onclick="insertSmilie(\'pin-cold.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-cold.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][20] = '<span onclick="insertSmilie(\'pin-colors.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-colors.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][21] = '<span onclick="insertSmilie(\'pin-crew.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-crew.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][22] = '<span onclick="insertSmilie(\'pin-crotal.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-crotal.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][23] = '<span onclick="insertSmilie(\'pin-cruel.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-cruel.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][24] = '<span onclick="insertSmilie(\'pin-cry.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-cry.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][25] = '<span onclick="insertSmilie(\'pin-cthulhu.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-cthulhu.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][26] = '<span onclick="insertSmilie(\'pin-devil.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-devil.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][27] = '<span onclick="insertSmilie(\'pin-dodo.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-dodo.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][28] = '<span onclick="insertSmilie(\'pin-dsk.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-dsk.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][29] = '<span onclick="insertSmilie(\'pin-faya1.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-faya1.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][30] = '<span onclick="insertSmilie(\'pin-faya2.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-faya2.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][31] = '<span onclick="insertSmilie(\'pin-freaky.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-freaky.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][32] = '<span onclick="insertSmilie(\'pin-fukushima.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-fukushima.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][33] = '<span onclick="insertSmilie(\'pin-funk.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-funk.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][34] = '<span onclick="insertSmilie(\'pin-glasses.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-glasses.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][35] = '<span onclick="insertSmilie(\'pin-globe.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-globe.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][36] = '<span onclick="insertSmilie(\'pin-halu.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-halu.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][37] = '<span onclick="insertSmilie(\'pin-indian.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-indian.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][38] = '<span onclick="insertSmilie(\'pin-jump.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-jump.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][39] = '<span onclick="insertSmilie(\'pin-justine.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-justine.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][40] = '<span onclick="insertSmilie(\'pin-lapin.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-lapin.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][41] = '<span onclick="insertSmilie(\'pin-laught.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-laught.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][42] = '<span onclick="insertSmilie(\'pin-like.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-like.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][43] = '<span onclick="insertSmilie(\'pin-love.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-love.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][44] = '<span onclick="insertSmilie(\'pin-lucha.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-lucha.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][45] = '<span onclick="insertSmilie(\'pin-mad1.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-mad1.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][46] = '<span onclick="insertSmilie(\'pin-mad2.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-mad2.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][47] = '<span onclick="insertSmilie(\'pin-marin.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-marin.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][48] = '<span onclick="insertSmilie(\'pin-mcc.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-mcc.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][49] = '<span onclick="insertSmilie(\'pin-medieval.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-medieval.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][50] = '<span onclick="insertSmilie(\'pin-milliards.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-milliards.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][51] = '<span onclick="insertSmilie(\'pin-munch.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-munch.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][52] = '<span onclick="insertSmilie(\'pin-muscles.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-muscles.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][53] = '<span onclick="insertSmilie(\'pin-mustache.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-mustache.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][54] = '<span onclick="insertSmilie(\'pin-nerd.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-nerd.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][55] = '<span onclick="insertSmilie(\'pin-neutral.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-neutral.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][56] = '<span onclick="insertSmilie(\'pin-ninjabite.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-ninjabite.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][57] = '<span onclick="insertSmilie(\'pin-oreilles.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-oreilles.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][58] = '<span onclick="insertSmilie(\'pin-pepin.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-pepin.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][59] = '<span onclick="insertSmilie(\'pin-pirate.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-pirate.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][60] = '<span onclick="insertSmilie(\'pin-plflplflp.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-plflplflp.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][61] = '<span onclick="insertSmilie(\'pin-pumpkin.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-pumpkin.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][62] = '<span onclick="insertSmilie(\'pin-pyjama.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-pyjama.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][63] = '<span onclick="insertSmilie(\'pin-pyramid.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-pyramid.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][64] = '<span onclick="insertSmilie(\'pin-rabbin.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-rabbin.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][65] = '<span onclick="insertSmilie(\'pin-red.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-red.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][66] = '<span onclick="insertSmilie(\'pin-reverse.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-reverse.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][67] = '<span onclick="insertSmilie(\'pin-saint.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-saint.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][68] = '<span onclick="insertSmilie(\'pin-santa.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-santa.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][69] = '<span onclick="insertSmilie(\'pin-shine.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-shine.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][70] = '<span onclick="insertSmilie(\'pin-skull1.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-skull1.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][71] = '<span onclick="insertSmilie(\'pin-skull2.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-skull2.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][72] = '<span onclick="insertSmilie(\'pin-skull3.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-skull3.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][73] = '<span onclick="insertSmilie(\'pin-social.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-social.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][74] = '<span onclick="insertSmilie(\'pin-sorel.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-sorel.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][75] = '<span onclick="insertSmilie(\'pin-sort.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-sort.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][76] = '<span onclick="insertSmilie(\'pin-sournois.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-sournois.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][77] = '<span onclick="insertSmilie(\'pin-sun.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-sun.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][78] = '<span onclick="insertSmilie(\'pin-three.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-three.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][79] = '<span onclick="insertSmilie(\'pin-t.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-t.png" /></span>';
arrSmilies["organic - Sons of the Ananas"][80] = '<span onclick="insertSmilie(\'pin-uzi.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-uzi.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][81] = '<span onclick="insertSmilie(\'pin-whoomp.jpg\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-whoomp.jpg" /></span>';
arrSmilies["organic - Sons of the Ananas"][82] = '<span onclick="insertSmilie(\'pin-worm.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-worm.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][83] = '<span onclick="insertSmilie(\'pin-yinyang.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-yinyang.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][84] = '<span onclick="insertSmilie(\'pin-zombie-1.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-zombie-1.gif" /></span>';
arrSmilies["organic - Sons of the Ananas"][85] = '<span onclick="insertSmilie(\'pin-zombie.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/organic - Sons of the Ananas/pin-zombie.gif" /></span>';
arrSmilies["otro - fruits"] = [];
arrSmilies["otro - fruits"][0] = '<span onclick="insertSmilie(\'grapp01.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/grapp01.gif" /></span>';
arrSmilies["otro - fruits"][1] = '<span onclick="insertSmilie(\'grapp02.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/grapp02.gif" /></span>';
arrSmilies["otro - fruits"][2] = '<span onclick="insertSmilie(\'grapp03.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/grapp03.gif" /></span>';
arrSmilies["otro - fruits"][3] = '<span onclick="insertSmilie(\'grapp04.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/grapp04.gif" /></span>';
arrSmilies["otro - fruits"][4] = '<span onclick="insertSmilie(\'grapp05.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/grapp05.gif" /></span>';
arrSmilies["otro - fruits"][5] = '<span onclick="insertSmilie(\'grapp06.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/grapp06.gif" /></span>';
arrSmilies["otro - fruits"][6] = '<span onclick="insertSmilie(\'pin01.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/pin01.gif" /></span>';
arrSmilies["otro - fruits"][7] = '<span onclick="insertSmilie(\'pin02.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/pin02.gif" /></span>';
arrSmilies["otro - fruits"][8] = '<span onclick="insertSmilie(\'pin03.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/pin03.gif" /></span>';
arrSmilies["otro - fruits"][9] = '<span onclick="insertSmilie(\'pin04.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/pin04.gif" /></span>';
arrSmilies["otro - fruits"][10] = '<span onclick="insertSmilie(\'pin05.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/pin05.gif" /></span>';
arrSmilies["otro - fruits"][11] = '<span onclick="insertSmilie(\'pin06.gif\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/otro - fruits/pin06.gif" /></span>';
arrSmilies["Shobo Shobo"] = [];
arrSmilies["Shobo Shobo"][0] = '<span onclick="insertSmilie(\'shoboshobo-01.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-01.png" /></span>';
arrSmilies["Shobo Shobo"][1] = '<span onclick="insertSmilie(\'shoboshobo-02.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-02.png" /></span>';
arrSmilies["Shobo Shobo"][2] = '<span onclick="insertSmilie(\'shoboshobo-03.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-03.png" /></span>';
arrSmilies["Shobo Shobo"][3] = '<span onclick="insertSmilie(\'shoboshobo-04.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-04.png" /></span>';
arrSmilies["Shobo Shobo"][4] = '<span onclick="insertSmilie(\'shoboshobo-05.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-05.png" /></span>';
arrSmilies["Shobo Shobo"][5] = '<span onclick="insertSmilie(\'shoboshobo-06.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-06.png" /></span>';
arrSmilies["Shobo Shobo"][6] = '<span onclick="insertSmilie(\'shoboshobo-07.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-07.png" /></span>';
arrSmilies["Shobo Shobo"][7] = '<span onclick="insertSmilie(\'shoboshobo-08.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-08.png" /></span>';
arrSmilies["Shobo Shobo"][8] = '<span onclick="insertSmilie(\'shoboshobo-09.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-09.png" /></span>';
arrSmilies["Shobo Shobo"][9] = '<span onclick="insertSmilie(\'shoboshobo-10.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-10.png" /></span>';
arrSmilies["Shobo Shobo"][10] = '<span onclick="insertSmilie(\'shoboshobo-11.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-11.png" /></span>';
arrSmilies["Shobo Shobo"][11] = '<span onclick="insertSmilie(\'shoboshobo-12.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-12.png" /></span>';
arrSmilies["Shobo Shobo"][12] = '<span onclick="insertSmilie(\'shoboshobo-13.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-13.png" /></span>';
arrSmilies["Shobo Shobo"][13] = '<span onclick="insertSmilie(\'shoboshobo-14.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-14.png" /></span>';
arrSmilies["Shobo Shobo"][14] = '<span onclick="insertSmilie(\'shoboshobo-15.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-15.png" /></span>';
arrSmilies["Shobo Shobo"][15] = '<span onclick="insertSmilie(\'shoboshobo-16.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-16.png" /></span>';
arrSmilies["Shobo Shobo"][16] = '<span onclick="insertSmilie(\'shoboshobo-17.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-17.png" /></span>';
arrSmilies["Shobo Shobo"][17] = '<span onclick="insertSmilie(\'shoboshobo-18.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-18.png" /></span>';
arrSmilies["Shobo Shobo"][18] = '<span onclick="insertSmilie(\'shoboshobo-19.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-19.png" /></span>';
arrSmilies["Shobo Shobo"][19] = '<span onclick="insertSmilie(\'shoboshobo-20.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-20.png" /></span>';
arrSmilies["Shobo Shobo"][20] = '<span onclick="insertSmilie(\'shoboshobo-21.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-21.png" /></span>';
arrSmilies["Shobo Shobo"][21] = '<span onclick="insertSmilie(\'shoboshobo-22.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-22.png" /></span>';
arrSmilies["Shobo Shobo"][22] = '<span onclick="insertSmilie(\'shoboshobo-23.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-23.png" /></span>';
arrSmilies["Shobo Shobo"][23] = '<span onclick="insertSmilie(\'shoboshobo-24.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-24.png" /></span>';
arrSmilies["Shobo Shobo"][24] = '<span onclick="insertSmilie(\'shoboshobo-25.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-25.png" /></span>';
arrSmilies["Shobo Shobo"][25] = '<span onclick="insertSmilie(\'shoboshobo-26.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-26.png" /></span>';
arrSmilies["Shobo Shobo"][26] = '<span onclick="insertSmilie(\'shoboshobo-27.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-27.png" /></span>';
arrSmilies["Shobo Shobo"][27] = '<span onclick="insertSmilie(\'shoboshobo-28.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-28.png" /></span>';
arrSmilies["Shobo Shobo"][28] = '<span onclick="insertSmilie(\'shoboshobo-29.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-29.png" /></span>';
arrSmilies["Shobo Shobo"][29] = '<span onclick="insertSmilie(\'shoboshobo-30.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-30.png" /></span>';
arrSmilies["Shobo Shobo"][30] = '<span onclick="insertSmilie(\'shoboshobo-31.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-31.png" /></span>';
arrSmilies["Shobo Shobo"][31] = '<span onclick="insertSmilie(\'shoboshobo-32.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-32.png" /></span>';
arrSmilies["Shobo Shobo"][32] = '<span onclick="insertSmilie(\'shoboshobo-33.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-33.png" /></span>';
arrSmilies["Shobo Shobo"][33] = '<span onclick="insertSmilie(\'shoboshobo-34.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-34.png" /></span>';
arrSmilies["Shobo Shobo"][34] = '<span onclick="insertSmilie(\'shoboshobo-35.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-35.png" /></span>';
arrSmilies["Shobo Shobo"][35] = '<span onclick="insertSmilie(\'shoboshobo-36.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-36.png" /></span>';
arrSmilies["Shobo Shobo"][36] = '<span onclick="insertSmilie(\'shoboshobo-37.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-37.png" /></span>';
arrSmilies["Shobo Shobo"][37] = '<span onclick="insertSmilie(\'shoboshobo-38.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-38.png" /></span>';
arrSmilies["Shobo Shobo"][38] = '<span onclick="insertSmilie(\'shoboshobo-39.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-39.png" /></span>';
arrSmilies["Shobo Shobo"][39] = '<span onclick="insertSmilie(\'shoboshobo-40.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-40.png" /></span>';
arrSmilies["Shobo Shobo"][40] = '<span onclick="insertSmilie(\'shoboshobo-41.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-41.png" /></span>';
arrSmilies["Shobo Shobo"][41] = '<span onclick="insertSmilie(\'shoboshobo-42.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-42.png" /></span>';
arrSmilies["Shobo Shobo"][42] = '<span onclick="insertSmilie(\'shoboshobo-43.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-43.png" /></span>';
arrSmilies["Shobo Shobo"][43] = '<span onclick="insertSmilie(\'shoboshobo-44.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-44.png" /></span>';
arrSmilies["Shobo Shobo"][44] = '<span onclick="insertSmilie(\'shoboshobo-45.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-45.png" /></span>';
arrSmilies["Shobo Shobo"][45] = '<span onclick="insertSmilie(\'shoboshobo-46.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-46.png" /></span>';
arrSmilies["Shobo Shobo"][46] = '<span onclick="insertSmilie(\'shoboshobo-47.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-47.png" /></span>';
arrSmilies["Shobo Shobo"][47] = '<span onclick="insertSmilie(\'shoboshobo-48.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-48.png" /></span>';
arrSmilies["Shobo Shobo"][48] = '<span onclick="insertSmilie(\'shoboshobo-49.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-49.png" /></span>';
arrSmilies["Shobo Shobo"][49] = '<span onclick="insertSmilie(\'shoboshobo-50.png\');" class="VanillaconsLink"><img src="/forum/extensions/Vanillacons/smilies/Shobo Shobo/shoboshobo-50.png" /></span>';
